### ISSUE TITLE
ToDo-List & Known Bug list (german)

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelswerk-Bot#2]
<details>
<summary>ToDo </summary>
<details>
<summary>Niedrige Priorität</summary>

- [ ] besseres /queue Design
- [ ] /schläft?
```
Args: <user>
Antwort:
user.name schläft oder ist seit mindestens ner Stunde offline. Was ein Weirdo!
bzw.
user.name schläft warscheinlich nicht
 ```

- [ ] player bzw nowplaying in editierbarer msg senden statt in einzelenen Messages
- [ ] suggestion command
- [ ] user join & user leave messages
- [ ] /help breite durch zb begrenzung der commands/zeile begrenzen
- [ ] help nichts gefunden meldung fix
- [ ] /autoplay, volume oder als arg
- [ ] /ping umbaun im music module per website
- [ ] Birthdays wie bei mee6
- [ ] .sad
- [ ] /skip option um song aus der queue zu löschen
- [ ] /embed
- [ ] /passwordgenerator
- [ ] /say guild option
- [ ] channelmute cmd der bei admins klappt
- [ ] /ping processing speed durch wie atlas
- [ ] /nowplaying
- [ ] custom uptime var mit now()
- [ ] Activity cmd mit emoji only msg filter
- [ ] ttt bot verschlechtern bzw difficulty
- [ ] l.topic
- [ ] funfact
- [ ] /link: verlinkt eine message und added einen button um direkt da hin zu springen
- [ ] (Starboard(?))
- [ ] /embed
</details>

<details>
<summary>Mittlere Priorität</summary>

- [ ] Bot bei /join oder /play nachfragen lassen, wenn schon in Benutzung
- [ ] /move
- [ ] bot soll musik pausieren wenn nieman im kanal is
- [ ] command adden zum leute vom bot blacklisten
- [ ] uptime message if music module is offline
- [ ] musikbotfeatures nur nutzbar machen wenn gleicher talk
- [ ] /repeat als alias für /loop + HANDLER
- [ ] /play playlist search
</details>

<details>
<summary>Hohe Priorität</summary>

-  [ ] Cooldown fixen

</details>
</details>

<details>
<summary>Commands und deren Bugs</summary>

- [ ] .bistududa
- [ ] .bistduweg
- [ ] /convert
- [ ] /dm
- [ ] easteregg
- [ ] .happy
- [ ] /hash
- [ ] .joke
- [ ] /joke
- [ ] /say
- [ ] .sleep

- [ ] /help
- [ ] /ping
- [ ] /lyrics
- [ ] .prefix
- [ ] /prefix
- [ ] .uptime
- [ ] .stats

- [ ] /ban
- [ ] /kick
- [ ] .purge
- [ ] /purge

- [ ] .afk
- [ ] /afk

- [ ] .reload
- [ ] .restart
- [ ] .eval
- [ ] .setactivity
</details>
